import { useState, useEffect } from 'react'import { useRouter } from 'next/router'import { getProducts } from '../lib/supabase'import { useAuth } from '../components/Layout'
const CATEGORIES = ['All', 'Automation', 'AI Tools', 'Business', 'Analytics', 'Templates']
const badgeMap = {  BESTSELLER: 'badge-gold', HOT: 'badge-red',  PREMIUM: 'badge-elite', NEW: 'badge-gold', ELITE: 'badge-elite',}
const StarRating = ({ rating }) => (  <span style={{ color: 'var(--gold)', fontSize: '0.75rem', letterSpacing: 2 }}>    {'★'.repeat(Math.floor(rating))}    <span style={{ color: 'var(--ash)', fontFamily: 'var(--font-mono)', fontSize: '0.6rem', marginLeft: 5 }}>      {rating}    </span>  </span>)
const ProductCard = ({ product, router }) => (  <div    className="card"    onClick={() => router.push(`/product/${product.slug}`)}    style={{ cursor: 'pointer', display: 'flex', flexDirection: 'column', height: '100%' }}  >    <div style={{ height: 3, background: 'linear-gradient(90deg, var(--blood), var(--gold-dim))' }}/>    <div style={{ padding: 28, flex: 1, display: 'flex', flexDirection: 'column' }}>      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>        <span style={{          fontFamily: 'var(--font-mono)', fontSize: '0.55rem',          color: 'var(--smoke)', letterSpacing: '0.18em', textTransform: 'uppercase',        }}>          {product.categories?.icon} {product.categories?.name}        </span>        {product.badge && <span className={`badge ${badgeMap[product.badge] || 'badge-ash'}`}>{product.badge}</span>}      </div>
      <h3 style={{        fontFamily: 'var(--font-display)', fontSize: '1.1rem',        color: 'var(--cream)', marginBottom: 10, letterSpacing: '0.04em',      }}>{product.name}</h3>
      <p style={{        fontFamily: 'var(--font-body)', fontSize: '0.875rem',        color: 'var(--ash)', lineHeight: 1.65, marginBottom: 20, flex: 1,        display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden',      }}>{product.description}</p>
      {/* Features preview */}      {product.features?.slice(0, 2).map(f => (        <div key={f} style={{          display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6,          fontFamily: 'var(--font-mono)', fontSize: '0.6rem', color: 'var(--smoke)',        }}>          <span style={{ color: 'var(--gold-dim)', fontSize: '0.5rem' }}>◆</span> {f}        </div>      ))}
      <hr className="divider" style={{ margin: '16px 0' }}/>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>        <div>          <div style={{            fontFamily: 'var(--font-display)', fontSize: '1.4rem',            color: 'var(--gold-shine)',          }}>            ${product.price}            {product.original_price && (              <span style={{                fontFamily: 'var(--font-mono)', fontSize: '0.65rem',                color: 'var(--smoke)', textDecoration: 'line-through', marginLeft: 8,              }}>${product.original_price}</span>            )}          </div>          <StarRating rating={product.rating} />        </div>        <button          className="btn btn-ghost btn-sm"          onClick={e => { e.stopPropagation(); router.push(`/product/${product.slug}`) }}        >          View →        </button>      </div>    </div>  </div>)
export default function StorePage() {  const router = useRouter()  const { user } = useAuth()  const [products, setProducts] = useState([])  const [filtered, setFiltered] = useState([])  const [category, setCategory] = useState('All')  const [search, setSearch] = useState('')  const [sort, setSort] = useState('featured')  const [loading, setLoading] = useState(true)
  useEffect(() => {    getProducts().then(({ data }) => {      setProducts(data || [])      setFiltered(data || [])      setLoading(false)    })  }, [])
  // Filter + sort  useEffect(() => {    let result = [...products]    if (category !== 'All') result = result.filter(p => p.categories?.name === category)    if (search) result = result.filter(p =>      p.name.toLowerCase().includes(search.toLowerCase()) ||      p.description?.toLowerCase().includes(search.toLowerCase())    )    if (sort === 'price-asc') result.sort((a, b) => a.price - b.price)    else if (sort === 'price-desc') result.sort((a, b) => b.price - a.price)    else if (sort === 'rating') result.sort((a, b) => b.rating - a.rating)    else if (sort === 'popular') result.sort((a, b) => b.total_sales - a.total_sales)    else result.sort((a, b) => (b.is_featured ? 1 : 0) - (a.is_featured ? 1 : 0))    setFiltered(result)  }, [products, category, search, sort])
  return (    <div style={{ minHeight: '100vh' }}>      {/* Header */}      <div style={{        background: 'var(--obsidian)',        borderBottom: '1px solid var(--border-dim)',        padding: '56px 0 40px',      }}>        <div className="container">          <div className="section-label">◆ Browse</div>          <h1 className="section-title">The Store</h1>          <p style={{            fontFamily: 'var(--font-body)', fontStyle: 'italic',            color: 'var(--ash)', marginTop: 10, fontSize: '1.05rem',          }}>            Premium digital tools. Instant delivery. Zero fluff.          </p>
          {/* Login notice for guests */}          {!user && (            <div style={{              marginTop: 24,              padding: '14px 20px',              border: '1px solid var(--gold-dim)',              background: 'rgba(184,150,12,0.04)',              display: 'flex', alignItems: 'center', gap: 12,              fontFamily: 'var(--font-mono)', fontSize: '0.65rem',              color: 'var(--gold)', letterSpacing: '0.1em',              maxWidth: 560,            }}>              <span style={{ fontSize: '1rem' }}> </span>              <span>Browse freely — <strong>sign in</strong> to purchase and access downloads.</span>              <button                className="btn btn-gold btn-sm"                style={{ marginLeft: 'auto', flexShrink: 0 }}                onClick={() => router.push('/login')}              >Sign In</button>            </div>          )}        </div>      </div>
      <div className="container" style={{ padding: '40px 24px' }}>        {/* Controls */}        <div style={{          display: 'flex', gap: 16, marginBottom: 36,          flexWrap: 'wrap', alignItems: 'center',          justifyContent: 'space-between',        }}>          {/* Search */}          <input            className="inp"            placeholder="Search products..."            value={search}            onChange={e => setSearch(e.target.value)}            style={{ maxWidth: 280, width: '100%' }}          />
          {/* Sort */}          <select            value={sort}            onChange={e => setSort(e.target.value)}            style={{              background: 'var(--iron)',              border: '1px solid var(--border)',              borderBottom: '1px solid var(--gold-dim)',              color: 'var(--cream)',              fontFamily: 'var(--font-mono)',              fontSize: '0.7rem',              padding: '10px 16px',              outline: 'none',              cursor: 'pointer',              letterSpacing: '0.08em',            }}          >            <option value="featured">Featured First</option>            <option value="popular">Most Popular</option>            <option value="rating">Top Rated</option>            <option value="price-asc">Price: Low → High</option>            <option value="price-desc">Price: High → Low</option>          </select>        </div>
        {/* Category filters */}        <div style={{          display: 'flex', gap: 10, marginBottom: 40,          flexWrap: 'wrap',        }}>          {CATEGORIES.map(cat => (            <button              key={cat}              onClick={() => setCategory(cat)}              style={{                background: category === cat ? 'var(--gold)' : 'transparent',                color: category === cat ? 'var(--void)' : 'var(--ash)',                border: `1px solid ${category === cat ? 'var(--gold)' : 'var(--border)'}`,                fontFamily: 'var(--font-mono)',                fontSize: '0.6rem',                letterSpacing: '0.15em',                textTransform: 'uppercase',                padding: '8px 18px',                cursor: 'pointer',                transition: 'all 0.2s',              }}            >{cat}</button>          ))}        </div>
        {/* Results count */}        <div style={{          fontFamily: 'var(--font-mono)', fontSize: '0.6rem',          color: 'var(--smoke)', letterSpacing: '0.15em',          textTransform: 'uppercase', marginBottom: 24,        }}>          {filtered.length} product{filtered.length !== 1 ? 's' : ''} found        </div>
        {/* Grid */}        {loading ? (          <div style={{ textAlign: 'center', padding: '80px 0' }}>            <div className="spinner" style={{ margin: '0 auto 16px', width: 32, height: 32 }}/>            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--smoke)', letterSpacing: '0.2em' }}>              Loading products...            </div>          </div>        ) : filtered.length === 0 ? (          <div style={{ textAlign: 'center', padding: '80px 0' }}>            <div style={{ fontSize: '2.5rem', marginBottom: 16 }}>◇</div>            <div style={{ fontFamily: 'var(--font-display)', fontSize: '1.2rem', color: 'var(--ash)' }}>              No products found            </div>            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--smoke)', marginTop: 8 }}>              Try a different search or category            </div>          </div>        ) : (          <div className="grid-products">            {filtered.map(p => (              <ProductCard key={p.id} product={p} router={router} />            ))}          </div>        )}      </div>    </div>  )}
